# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: searchInventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15searchInventory.proto\x12\x06search\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x08Products\x12 \n\x07product\x18\x01 \x03(\x0b\x32\x0f.search.Product\"S\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x32K\n\x0fInventorySearch\x12\x38\n\x11GetServerResponse\x12\x0f.search.Message\x1a\x10.search.Products\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_PRODUCTS = DESCRIPTOR.message_types_by_name['Products']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'searchInventory_pb2'
  # @@protoc_insertion_point(class_scope:search.Message)
  })
_sym_db.RegisterMessage(Message)

Products = _reflection.GeneratedProtocolMessageType('Products', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTS,
  '__module__' : 'searchInventory_pb2'
  # @@protoc_insertion_point(class_scope:search.Products)
  })
_sym_db.RegisterMessage(Products)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'searchInventory_pb2'
  # @@protoc_insertion_point(class_scope:search.Product)
  })
_sym_db.RegisterMessage(Product)

_INVENTORYSEARCH = DESCRIPTOR.services_by_name['InventorySearch']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=33
  _MESSAGE._serialized_end=59
  _PRODUCTS._serialized_start=61
  _PRODUCTS._serialized_end=105
  _PRODUCT._serialized_start=107
  _PRODUCT._serialized_end=190
  _INVENTORYSEARCH._serialized_start=192
  _INVENTORYSEARCH._serialized_end=267
# @@protoc_insertion_point(module_scope)
